import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next";
import { getUserFromCookie } from "@/lib/auth";
import { UserProvider } from "./context/UserContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "AI-Interview",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const user = await getUserFromCookie();

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Toaster />
                <UserProvider user={user}>{children}</UserProvider>
                <Analytics />
            </body>
        </html>
    );
}
